version: "3.7"
services:

  backend:
    image: flask-demo:latest
    restart: always
    volumes:
      - "../flask-demo:/usr/local/src/flask-demo"
      - "/etc/localtime:/etc/localtime"
    ports:
      - 5000:5000